# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='descrição')),
                ('is_active', models.BooleanField(verbose_name='ativa')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
    ]
