# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('T', 'Todos')], default='S', max_length=1, verbose_name='tipo'),
        ),
    ]
