# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativa'),
        ),
    ]
