# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_auto_20171018_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=40, unique=True, verbose_name='descrição'),
        ),
    ]
