# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Se ativo o usuário tem permissão para acessar o sistema', verbose_name='ativo'),
        ),
    ]
